server:
  port: 7001
spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qysl123/spring-cloud-config.git
          searchPaths: '{application}'  #搜索各个以服务名命名的文件夹下的所有yml
eureka:
  instance:
    hostname: localhost
    instance-id: localhost:7001
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/  #注册中心地址