eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
spring:
  application:
    name: gateway
server:
  port: 5555
zuul:
  routes:
    service0: /service/0/**
    service1: /service/1/**

